site_name: GTMRG Wiki
site_url: https://gt-marine-robotics-group.github.io
nav:
  - Home: index.md
  - Nova Motor Controller:
    - Firmware: nova/firmware.md
    - Supernova v1: nova/supernova.md
  - Dev Ops:
    - Software Guide: devops/guide.md
    - Networking: devops/networking.md
    - ROS2: 
      - Getting Started: devops/ros/getting-started.md
  - Fleet:
    - Archive:
      - ASV2016 Vinny: fleet/archive/asv2016-vinny
theme: readthedocs

